name: Build XML & MD5

on:
  push:
    paths:
      - 'datasets/sztabowa/*.xlsx'
      - '.scripts/**'
      - '.github/workflows/generate-xml.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build XML & MD5
        run: python .scripts/build_xml.py

      - name: Commit XML & MD5
        run: |
          git config user.name "matheo-bot"
          git config user.email "actions@users.noreply.github.com"
          git add Matheo_Invest_dane.xml Matheo_Invest_dane.md5
          git commit -m "Build XML & MD5" || echo "No changes"
          git push
          
